"""Generate one small PBS job per experiment, from a single table.

Ten hand-maintained .pbs files would drift -- that failure has already cost this
project a queue slot twice (a stale `#PBS -A` placeholder, and a README telling
people to sed a variable that no longer existed). So the jobs are GENERATED and
the table below is the only place to edit.

Each job: its own output directory, its own walltime, sized for the debug queue
where it fits. Rerun this script after changing the table.
"""
import pathlib
import stat

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "polaris" / "jobs"

#  name             script                     argv  queue        walltime  decides
JOBS = [
    ("gate",   "test_correctness.py",            "", "debug",       "00:20:00",
     "GATE -- nothing else means anything if this fails"),
    ("cell3",  "exp8_three_cells.py",           "3", "debug",       "00:20:00",
     "the ONLY parameter-free falsifier in the set"),
    ("gonogo", "exp0_gonogo.py",                 "", "debug",       "00:30:00",
     "headline, fresh-compiled FlexAttention baseline"),
    ("cells",  "exp8_three_cells.py",            "", "debug",       "00:40:00",
     "all three cells, paired/interleaved timing"),
    ("fixed",  "exp9_fixed_cost.py",             "", "debug",       "00:40:00",
     "out-of-sample test of the fixed-cost account"),
    ("imbal",  "exp7_load_imbalance.py",         "", "debug",       "00:30:00",
     "counting vs makespan, with a wave-count control"),
    ("select", "exp3_selection.py",              "", "debug",       "00:50:00",
     "does the wall-clock argmin match the element argmin"),
    ("amort",  "exp5_amortisation.py",           "", "debug",       "00:40:00",
     "permutation once-per-forward (PREFILL ONLY)"),
    ("tiles",  "exp1_tile_shape.py",             "", "debug",       "00:50:00",
     "p(BQ,A,mask) -- read ACROSS masks, not down a column"),
    ("classa", "exp2_class_a.py",                "", "debug",       "00:30:00",
     "class A across tile shapes"),
    # heavy: 3 masks x 5 tiles x 9 gather variants. Does not fit the debug hour.
    ("traffic", "exp6_traffic_multiplier.py",    "", "preemptable", "01:30:00",
     "LOWER BOUND on a class that is modelled, not implemented"),
]

TEMPLATE = """#!/bin/bash -l
#PBS -N pa-{name}
#PBS -q {queue}
#PBS -l select=1:system=polaris
#PBS -l place=scatter
#PBS -l walltime={walltime}
#PBS -l filesystems=home:eagle
#PBS -j oe
#PBS -o logs/

# {decides}
#
# GENERATED by tools/gen_polaris_jobs.py -- edit the table there, not this file.
# Submit:  qsub -A <project> polaris/jobs/{name}.pbs
# Output:  results/{name}/<stamp>/

set -uo pipefail
cd "${{PBS_O_WORKDIR:-$PWD}}"
mkdir -p logs

if [ -f polaris/env.generated.sh ]; then . polaris/env.generated.sh; else
  echo "FATAL: run polaris/setup.sh on a login node first." >&2; exit 1; fi
module use /soft/modulefiles
set +u
module --ignore_cache load "${{POLYATTN_MODULE:-conda}}" 2>/dev/null || \\
  echo "WARN: module load failed, continuing -- the venv is what matters." >&2
conda activate base 2>/dev/null || true
source "$POLYATTN_VENV/bin/activate"
set -u

# Pin the host compiler: when the module load fails, PrgEnv-nvidia's nvc is
# picked, rejects -Wno-psabi, and kills every inductor compile -- which once
# looked like a FlexAttention bug and cost a whole diagnostic job.
command -v gcc >/dev/null && export CC="$(command -v gcc)" CXX="$(command -v g++)"

export CUDA_VISIBLE_DEVICES=0
export TRITON_CACHE_DIR="$PWD/.triton-cache-$PBS_JOBID"
export TORCHINDUCTOR_CACHE_DIR="$PWD/.inductor-cache-$PBS_JOBID"

STAMP="$(date +%Y%m%d-%H%M%S)-${{PBS_JOBID%%.*}}"
D="results/{name}/$STAMP"
mkdir -p "$D"
ln -sfn "$STAMP" "results/{name}/latest"

{{
  echo "job     {name}"
  echo "decides {decides}"
  echo "script  gpu/{script} {argv}"
  echo "host    $(hostname)"
  echo "when    $(date -Is)"
  echo "cc      ${{CC:-<unset>}}"
  nvidia-smi --query-gpu=name,compute_cap --format=csv,noheader
}} > "$D/meta.txt"
cat "$D/meta.txt"

python gpu/env_check.py > "$D/env.txt" 2>&1
python gpu/{script} {argv} > "$D/out.txt" 2>&1
rc=$?
echo "exit $rc" >> "$D/meta.txt"
echo; echo "---------------- $D/out.txt ----------------"
cat "$D/out.txt"
exit $rc
"""

SUBMIT = """#!/usr/bin/env bash
# Submit every job. The gate goes first; everything else waits for it to PASS and
# then runs CONCURRENTLY -- ten small debug-queue jobs schedule far sooner than
# one three-hour block, and a failure or preemption costs one experiment.
#
#   ./polaris/submit_all.sh <project>            # gate + all, dependent
#   ./polaris/submit_all.sh <project> cell3 fixed  # just these, still after gate
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
A="${1:?usage: submit_all.sh <project> [job ...]}"; shift || true

GATE=$(qsub -A "$A" polaris/jobs/gate.pbs)
echo "gate           $GATE"

want=("$@")
for f in polaris/jobs/*.pbs; do
  n=$(basename "$f" .pbs); [ "$n" = gate ] && continue
  if [ ${#want[@]} -gt 0 ]; then
    printf '%s\\n' "${want[@]}" | grep -qx "$n" || continue
  fi
  id=$(qsub -A "$A" -W depend=afterok:"$GATE" "$f")
  printf '%-14s %s\\n' "$n" "$id"
done
echo
echo "watch:   qstat -u \\$USER"
echo "results: results/<job>/latest/out.txt"
"""


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for name, script, argv, queue, walltime, decides in JOBS:
        p = OUT / f"{name}.pbs"
        p.write_text(TEMPLATE.format(name=name, script=script, argv=argv,
                                     queue=queue, walltime=walltime,
                                     decides=decides))
        p.chmod(p.stat().st_mode | stat.S_IEXEC)
        (REPO / "results" / name).mkdir(parents=True, exist_ok=True)
    s = REPO / "polaris" / "submit_all.sh"
    s.write_text(SUBMIT)
    s.chmod(s.stat().st_mode | stat.S_IEXEC)
    print(f"wrote {len(JOBS)} jobs to polaris/jobs/ and polaris/submit_all.sh")
    for name, _, _, q, w, d in JOBS:
        print(f"  {name:<9} {q:<12} {w}  {d}")


if __name__ == "__main__":
    main()
